### ISSUE TITLE
What is user ID?

### ISSUE THREAD

**Issue by gh-o-st** [rytr-me/documentation#1]
In the readme, you mention:

> For `userId` you need to supply `user ID` from your database, eg: primary key for `users` database table.

I'm confused as to what database you're referring to, and furthermore, why this tool would seek to connect to, or know PII from that database, I don't understand?

**Comment by atulmy** [comment]
Hello, it is mandatory to supply unique userId with each call. This helps prevent spam/abuse of service. Instead of primary key, you can create alternative unique key for each user and supply that.

**Comment by gh-o-st** [comment]
Ah, so this is a unique ID in addition to the API key, yes?

**Comment by gh-o-st** [comment]
Essentially, what I'm asking is "is there a right answer" that I need to pass as the `userId` or if any unique value is good?

**Comment by atulmy** [comment]
It should come from your `users` table, ideally it should be primary key of the table. However in case you want to not share that, you can generate unique keys for each user just for the API calls and supply that.

**Comment by gh-o-st** [comment]
Ok, gotcha. Is this so that API usage can be tracked on a user by user basis? I'm just confused as to its purpose.

**Comment by atulmy** [comment]
> Is this so that API usage can be tracked on a user by user basis?
No, it is being supplied to the A.I. engine.

API key is identifier for the API consumer account, for each of your customers, you need to supply the `userId`

**Comment by gh-o-st** [comment]
Gotcha. I understand now. Thanks!
