### ISSUE TITLE
API params confusion!

### ISSUE THREAD

**Issue by Daniyaldehleh** [rytr-me/documentation#2]
HI Atul,

I'd like to have a response with the following params:
![Screen Shot 2022-04-28 at 12 19 36 PM](https://user-images.githubusercontent.com/58639693/165798614-0abcac3c-ef49-4fff-a2c4-15781e1e8f79.png)
where
lang: English, tone: appreciative,user case: testimonial & review, name: HelloName, Review Title: Positive App Review, number of variant:3 

The following api requests doesn't seem to work:
```
fetch(
  `https://api.rytr.me`,
  {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authentication: `Bearer <>`      
    },
    body: {
      languageId: "607adac76f8fe5000c1e636d",
      toneId: "6058207530f7b1000c1c4f86", //appreciative
      useCaseId:"607c7ae91ebe15000cbbc7af",
      inputContexts:"positive app review",
      variations: 3,
    }
  }
)
  .then((res) => res.json())
  .then(console.log)
  .catch(console.log);
```
Please let me know what I did wrong or what I should do instead to make it work. Thanks :)

**Comment by gh-o-st** [comment]
@Daniyaldehleh, a couple things I'm seeing is that your API url doesn't include `v1` or the `ryte` endpoint
Also, it looks like you omitted the `user` parameter, which I found out from my issue, is required
And lastly, you have to remember to pass the input names/values (key/val) pairs... I was never able to find documentation about the names of each possible field that we need to pass with our requests, so I've resorted to watching network traffic during each action I take on Rytr.me to find the correct input names.

![image](https://user-images.githubusercontent.com/6260598/165814267-6886f480-955e-40c5-9155-a5e7f31e4ecc.png)


Try something kinda like this: 
(untested theoretical code)
  
``` JS
  fetch(
  `https://api.rytr.me/v1/ryte`,
  {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authentication: `Bearer <API KEY>`      
    },
    body: {
      languageId: "607adac76f8fe5000c1e636d", 
      toneId: "6058207530f7b1000c1c4f86", 
      useCaseId: "607c7ae91ebe15000cbbc7af", 
      inputContexts: {
        NAME_LABEL: "HelloName"
        REVIEW_TITLE_LABEL: "Positive App Review"
      },
      variations": 3, 
      userId: "<ENTER ANY UNIQUE USER ID>", 
      format: "html", 
      creativityLevel: "default"
    }
  }
)
  .then((res) => res.json())
  .then(console.log)
  .catch(console.log);
```

**Comment by gh-o-st** [comment]
Also, I just happened to notice that it looks like they're not even passing `useCaseId` and instead passing it as `typeId`

**Comment by Daniyaldehleh** [comment]
Hi @gh-o-st !
Thanks for your quick reply,
I tried your code, 

```
fetch(
    `https://api.rytr.me/v1/ryte`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authentication: `Bearer <API_TOKEN>`      
      },
      body: {
        languageId: "607adac76f8fe5000c1e636d", 
        toneId: "6058207530f7b1000c1c4f86", 
        useCaseId: "607c7ae91ebe15000cbbc7af", 
        inputContexts: {
          NAME_LABEL: "HelloName",
          REVIEW_TITLE_LABEL: "Positive App Review"
        },
        variations: 3, 
        userId: "USER11234", 
        format: "html", 
        creativityLevel: "default"
      }
    }
  )
    .then((res) => res.json())
    .then(console.log)
    .catch(console.log);
```
yet I got:
```
POST https://api.rytr.me/v1/ryte net::ERR_FAILED
(anonymous) @ VM974:1
TypeError: Failed to fetch
    at <anonymous>:1:1
```

**Comment by gh-o-st** [comment]
Just so that there's no confusion, I want to clarify that you are, in fact, actually replacing `<API_TOKEN>` with your real API key, correct?

**Comment by Daniyaldehleh** [comment]
Hey!
Ghost, I am not sure what you mean by real but I am using the token key I've for my rytr account
