### ISSUE TITLE
Invalid language id

### ISSUE THREAD

**Issue by ykovalenko-gentech** [rytr-me/documentation#6]
Hello I'm using api with subscription. Trying to generate text, but all the time is getting response with any language id
`{
    "success": false,
    "message": "Invalid languageId."
}`.

All entity ids I got from other endpoints and many times ensured that it's exactly the same and no typo is present.

Payload example:
`{
    "toneId": "607adbdf6f8fe5000c1e6378",
    "useCaseId": "6062df03e20e7d000c15609b",
    "inputContexts": {
        "BUSINESS_IDEA_LABEL": "Powerful Ad Automation Software for Facebook and TikTok AdBraze"
    },
    "variations": 1,
    "userId": "31232141231",
    "format": "text",
    "languageId": "607adac76f8fe5000c1e636d",
    "creativityLevel": "none"
}`

Please point me where I have mistake.

**Comment by atulmy** [comment]
As the error message suggests, you are missing the `languageId` parameter when calling the API.
